apiVersion: apps/v1
kind: Deployment
metadata:
   name: mydep
   
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      name: my-pod1
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-cont
          image: pburela/demoapp-pipeline:latest
          imagePullPolicy: always
          port: 
