apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: my-app

spec:
  selector:
    app: my-app
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 30036 
      port: 80
      targetPort: 9099
